
modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="http://my.issue.tracker/"


[[mods]]

modId="birdsneststres"
version="1.0.1"
displayName="Birds Nests & Treasures"
# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/FizixInt/Birds-Nests-Treasures"
# logoFile="examplemod.png"
credits="FIZIX"
authors="FIZIX"

description='''
Birds Nests & Treasures is a random treasure mod inspired by and that expands upon the "Birds Nests" Mod by Clever Panda.

Birds Nests & Treasures adds a number of collectable treasures to the world that can be found while exploring; such as Birds Nests, Bandit Treasure
Pouches, Sunken Treasure Bottles and Ancient Treasures. If you find any of these items, simply right click while holding to open them and contain the
treasures within.
'''

# Dependencies
[[dependencies.birdsneststres]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.birdsneststres]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"


